# Generated by Django 3.1.5 on 2021-08-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
